### ISSUE TITLE
Tag not added  with the new markdown engine ?

### ISSUE THREAD

**Issue by iunctis** [discourse/discourse-affiliate#4]
It seems that since the new markdown engine is in place the tag is not added into ldlc and amazon links. Since the `affiliate.js.es6` files is in discourse-markdown, I think it is related to the new engine.

I can confirm this issue on two websites running on the latest version of Discourse.

The topic on meta.discourse.org seems to have disappeared, so I wanted to let you know here. It is not urgent tho, I'm sure you have a lot to do with the new engine compatibility

**Comment by SamSaffron** [comment]
You have to upgrade to latest discourse, affiliate is now inserted server
side

**Comment by iunctis** [comment]
I run on the latest version of Discourse available https://github.com/discourse/discourse/commit/14c2439473e52b467ac24504eaf1e617ff255df8

But maybe I have a conflict with another plugin. I'll try some things tomorrow night.

Sorry if I made a mistake but reporting a false issue.

**Comment by iunctis** [comment]
Ok I see what you meant. The tag is not generated on the preview, but added after the post is published. 

I closed the issue
